# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myazureemailservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_74d963f4a1674454b679e8f02dd2111e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_03b5df33dd734f888a6a2ebfcb59c98d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_74d963f4a1674454b679e8f02dd2111e }}/taha12k/emailservice_x86:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myazureemailservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_412e9b2e8a014a0f8498612ee66b7315 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_74d963f4a1674454b679e8f02dd2111e }}/taha12k/emailservice_x86:${{ github.sha }}'